# feeder
feeder: feeders.feeder_uav.Feeder
train_feeder_args:
  data_path: ../data/uav/MMVRAC_CSv1_angle.npz
  split: train
  debug: False
  random_choose: False
  random_shift: False
  random_move: False
  window_size: 64
  normalization: False
  random_rot: False
  p_interval: [0.5, 1]
  vel: False
  bone: False
  use_angle: True

test_feeder_args:
  data_path: ../data/uav/MMVRAC_CSv1_angle.npz
  split: test
  window_size: 64
  p_interval: [0.95]
  vel: False
  bone: False
  use_angle: True
  debug: False

# model
model: model.ske_mixf.Model
model_args:
  num_class: 155
  num_point: 17
  num_person: 2
  graph: graph.uav.Graph
  graph_args:
    labeling_mode: 'spatial'
  k: 1
  in_channels: 9

#optim
weight_decay: 0.0005
base_lr: 0.2
step: [35, 55, 75]
warm_up_epoch: 5

# training
device: 0
batch_size: 128
test_batch_size: 128
num_epoch: 90
nesterov: True
