# feeder
feeder: feeders.feeder_uav.Feeder
train_feeder_args:
  data_path: ./data/uav/province/train_joint.npy
  label_path: ./data/uav/province/train_label.npy
  random_choose: False
  random_shift: False
  random_move: False
  window_size: -1
  normalization: False
  debug: False

test_feeder_args:
  data_path: ./data/uav/province/test_A_joint.npy
  label_path: ./data/uav/province/test_A_label.npy

# model
model: model.ske_mixf.Model
model_args:
  num_class: 155
  num_point: 17
  num_person: 2
  graph: graph.uav.Graph
  graph_args:
    labeling_mode: 'spatial'

#optim
weight_decay: 0.0001
base_lr: 0.1
step: [30, 40]

# training
device: 0
batch_size: 32
test_batch_size: 32
num_epoch: 50
nesterov: True
